project:
  type: website
  resources: static
  output-dir: docs

website:
  google-analytics: "G-YMN4N6P546"
  title: "Data & Info Research@<b style=color:#000>OntarioTechU</b>"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.ipynb
      - href: articles/index.qmd
        text: Articles
      - about.qmd
  page-footer: "Database / AI / Workflow, 2025 Â©"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    anchor-sections: true
    number-sections: true
