project:
  type: website
  resources: static

website:
  title: "dB@<b style=color:#000>OntarioTechU</b>"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.ipynb
      - href: articles/index.qmd
        text: Articles
      - about.qmd
  page-footer: "
  <div class=footer>Database & Automated Workflow, 2025 Â©</div>
  "

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    anchor-sections: true
    number-sections: true
